# Generated by Django 5.1.2 on 2024-10-12 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_category_alter_product_id_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
