# Generated by Django 5.1.3 on 2024-12-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0007_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
