# Generated by Django 5.1.3 on 2024-12-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0009_purchase_price_alter_purchase_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='price',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
