# Generated by Django 5.1.3 on 2024-12-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0010_remove_purchase_order_id_remove_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='order_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
