# Generated by Django 5.1.3 on 2024-12-02 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0011_purchase_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='order_id',
        ),
    ]
