# Generated by Django 5.1.3 on 2024-12-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0012_remove_purchase_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
